# Generated by Django 5.1.4 on 2025-01-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_auctionlistings_bid_count_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlistings",
            name="bid_count",
        ),
        migrations.AddField(
            model_name="bids",
            name="bid_count",
            field=models.IntegerField(default=0),
        ),
    ]
